### ISSUE TITLE
Minor parentheses styling inconsistency

### ISSUE THREAD

**Issue by celerysticker** [algorithmsbooks/optimization#46]
On pg. 172, Example 10.3, in the first objective function, the second inner set of parentheses should be larger to match the style of the rest of the equations (e.g, ```\left( x_2 - \frac{3}{2} \right)```):

![image](https://user-images.githubusercontent.com/5707094/117759295-675afa80-b1d8-11eb-8476-8586a1be40c3.png)

**Comment by mykelk** [comment]
Fixed! I've reuploaded. Thanks!
