### ISSUE TITLE
Notation question

### ISSUE THREAD

**Issue by jomavera** [algorithmsbooks/optimization#48]
I have a question regarding the notation used in the Wolfe conditions. The armijo's condition is also written as f(x^(k+1)) <= f(x^(k))+ beta*alpha*grad_f(x^(k))^T* d^(k) and this is consistent with algorithm 4.2. But the first thing that comes to my mind when reading nabla_(d^(k)) f(x^(k)), in equation (4.4), is as the gradient of f(.) wrt d^(k). Is this equivalent to the dot product of grad_f(x^k) and d^(k)? 

Thanks!

**Comment by tawheeler** [comment]
Hello Jose,

Correct, the derivative there is a directional derivative as described in Equation 2.8. It is equivalent to the dot product of the grad of f and d (as shown in Equation 2.9).

Hope that helps!

**Comment by jomavera** [comment]
Oh I overlooked (2.9)! 😅 Thanks for making it clear.
