### ISSUE TITLE
Minor error

### ISSUE THREAD

**Issue by TSeyhan** [algorithmsbooks/optimization#52]
I was browsing your book and came across this minor error.

section 10.3, p171: You are not dividing by c_n when writing x_n as function of the other x. For brevity, you can define {c'}_i := c_i / c_n. Then you'll have x_n = - {c'}_1 x_1 - {c'}_2 x_2 - ... - {c'}_{n-1} x_{n-1}.

Cheers!

**Comment by tawheeler** [comment]
Thank you! Looks like we introduced this error when we changed this example over to a linear form. Should be fixed when we next re-upload the PDF.
