### ISSUE TITLE
Figure 10.7

### ISSUE THREAD

**Issue by hurak** [algorithmsbooks/optimization#53]
Page 175, figure 10.7: Not an error but since (10.23) motivated as lower bound for (10.22), it might be more appropriate to visualize not the plain linear function in Fig. 10.7 but rather a linear function truncated to zero for \mu<0.

**Comment by tawheeler** [comment]
Do you perhaps have a sketch for what you have in mind? Figure 10.7 does not vary in \mu, but in x.

**Comment by hurak** [comment]
Indeed, I expressed it in a confusing way. In fact, even the essence of my suggestion was incorrect and I have only realized it while trying to reformulate this issue (and I will not bother you by describing what was wrong in my reasoning). So in this regard I have again learned something. Thanks to your book and you :-)

Please ignore this "issue" altogether.

**Comment by tawheeler** [comment]
No worries!
