### ISSUE TITLE
Page 176: complementary slackness condition is not strict in general

### ISSUE THREAD

**Issue by hurak** [algorithmsbooks/optimization#54]
Page 176: the definition of complementary slackness preceding (10.30) states that **either** this **or** that is **zero**. But in general the complementary slackness condition does not require that only one of the two must be zero, does it? Strict complementary slackness is special and holds for LP but not for QP.

**Comment by tawheeler** [comment]
Thank you for your comment. Yes, as shown in equation 10.30, if both are zero, then complementary slackness holds. As such, the "or" is not mutually exclusive. We can throw in an "or both" if it helps clarify things.

**Comment by hurak** [comment]
Or just remove the "Either" at the beginning of the sentence. I think it does suggest mutual exclusivity of the subsequent "or".

**Comment by mykelk** [comment]
Good call. We can change to `, where $\mu_i$ is zero` ...

**Comment by tawheeler** [comment]
Thank you! Done.
