### ISSUE TITLE
Page Order in Chapter 6

### ISSUE THREAD

**Issue by aiyaher** [algorithmsbooks/optimization#59]
Not sure if this is intentional, but the ordering of pages 95-97 in Chapter 6 seems a little disjointed. Page 95 ends with the beginning of the Exercises section, page 96 is fully dedicated to Algorithm 6.5 (which is referenced on page 94), and then page 97 continues with the Exercises section.

**Comment by tawheeler** [comment]
Thank you aiyaher
Page layout in LaTeX is largely done automatically, with floating objects like Algorithm 6.5 ending up where they do based on a number of layout rules. Looks like this outcome may be a bit suboptimal.
We are not allowed to change pagination now that the book is out, but can certainly keep this in mind for a future new version.
