### ISSUE TITLE
Descriptions of Algorithms / Comments in Algorithms

### ISSUE THREAD

**Issue by chelseas** [algorithmsbooks/optimization#60]
I am opening another issue because students have been coming to me in office hours with confusion over the Julia code for the algorithms and requests for pseudo-code explanations. 
Here I am including for your consideration the marked up algorithm examples, versions of which I have sent to students to explain what is going on. 
[trust_region 1.pdf](https://github.com/algorithmsbooks/optimization/files/8509773/trust_region.1.pdf)

[algo_9.6_revision.pdf](https://github.com/algorithmsbooks/optimization/files/8509774/algo_9.6_revision.pdf)

This is not an algo description but what I think would be a more clear and precise description of the algorithm:
[algo textbook pg 151_revisions.pdf](https://github.com/algorithmsbooks/optimization/files/8509775/algo.textbook.pg.151_revisions.pdf)

**Comment by tawheeler** [comment]
Committed most of the changes from trust_region1.pdf

**Comment by tawheeler** [comment]
Committed many changes for alg 9.6

**Comment by tawheeler** [comment]
I'm not going to take the suggestion for the last pdf, as it will affect pagination. Also, whether it is uniformly at random or not is not really the point.  Yes, we implement it to be uniform, but you don't have to.

**Comment by mykelk** [comment]
Posted to the book site. Thanks!

**Comment by tawheeler** [comment]
"chosen at random" does not fit on the page without more work.

I thought about it overnight and changed "choose" to "sample".

**Comment by mykelk** [comment]
Sounds good to me! Thanks Tim and Chelsea!
