### ISSUE TITLE
n dimensional quadratic

### ISSUE THREAD

**Issue by chelseas** [algorithmsbooks/optimization#61]
Is this paragraph referring to an _n-dimensional_ quadratic? Because this detail seems important and it is not currently specified.

![image](https://user-images.githubusercontent.com/14879690/163942601-0d31c21f-82dd-4052-af2a-4769d9d46765.png)

**Comment by tawheeler** [comment]
One cannot have n mutually conjugate directions in a space smaller than n dimensions, so yes.

**Comment by chelseas** [comment]
Ok so are you going to clarify? I'm not sure the average student has it top of mind that you need to have a space of at least n dimensions. It's also a simple fix to say "an n-dimensional quadratic function" or "a quadratic function _in n dimensions_"

**Comment by chelseas** [comment]
It's already on a new line.

**Comment by chelseas** [comment]
I feel like sometimes  you can be a bit dismissive of my suggestions.

**Comment by tawheeler** [comment]
Okay, clearly you feel strongly about this issue. I will change "Recall that `n` line searches along mutually conjugate directions will optimize a quadratic function." to "Recall that `n` line searches along mutually conjugate directions will optimize an `n`-dimensional quadratic function."
