### ISSUE TITLE
pg. 168 - Hyperrectangle

### ISSUE THREAD

**Issue by alextzik** [algorithmsbooks/optimization#74]
Fig. 10.2 shows both two hyperrectangles and the set resulting from their subtraction, but it is not clear to which set the caption refers to as a hyperrectangle.

**Comment by tawheeler** [comment]
The figure only shows one hyperrectangle. The other one you may see is the figure's border. The dotted lines on inner box are the bracketing constraints, so I am going to consider this sufficient.
