### ISSUE TITLE
Algorithm 13.8 and Algorithm 13.9

### ISSUE THREAD

**Issue by minhnhathcmus** [algorithmsbooks/optimization#89]
In algorithm 13.8 (page 245), I think it should be rand(1:len(X)) instead of rand(1:m).
And in algorithm 13.9 (page 246), I think it should be StatsBase.sample! or something like the "choices" function in Python that returns a list with a random selection from the 1:len(X) sequence instead of only 1:m sequence.
![image](https://user-images.githubusercontent.com/75598786/169049129-f9676399-3a9e-452b-84eb-e1b554687bda.png)
![image](https://user-images.githubusercontent.com/75598786/169049156-b40622bf-76c8-4860-b96a-20c181005773.png)

**Comment by tawheeler** [comment]
Thank you! I am changing them to `S = [sample(X)]` and `S = sample(X, m, replace=false)` respectively.
