### ISSUE TITLE
dot and ⋅ in Conjugate Gradient Descent algorithm implementation

### ISSUE THREAD

**Issue by coopshea** [algorithmsbooks/optimization#91]
Hi, I could be totally off here, but I think the following line in step! for conjugate gradient descent could be a little inconsistent:

β = max(0, dot(g′, g′-g)/(g⋅g))

There is both the dot() and the ⋅ in the same line, which threw me off a little bit. Are these the same?

**Comment by mykelk** [comment]
Hmm... I'm good with that switch!

**Comment by tawheeler** [comment]
Done! Thanks Cooper.
