### ISSUE TITLE
formula (3.3)

### ISSUE THREAD

**Issue by tZougari** [algorithmsbooks/optimization#94]
Hi, am asking .. in page 38, the formula (3.3) should be  $\displaystyle  \frac{F_n}{F_{n-1}} = \varphi   \frac{1-s^n}{1-s^{n-1}}$
Thank you for the excelent book

**Comment by tawheeler** [comment]
You are correct! Thank you, will fix.

**Comment by tawheeler** [comment]
We typically include the names of those who have contributed fixes for the book. If you would like to added to the acknowledgements section, please let me know your first and last name.

**Comment by tZougari** [comment]
Oh thank you, it would be a pleasure,  and i ll show it to my optimization
students : )

my first name : Tarek
last name : Zougari


Le sam. 11 nov. 2023 à 04:23, Tim Wheeler ***@***.***> a
écrit :

**Comment by tawheeler** [comment]
Great! It will be reflected the next time we upload the textbook.
