### ISSUE TITLE
title of Al-Khawarizmi's book of Algebra

### ISSUE THREAD

**Issue by tZougari** [algorithmsbooks/optimization#95]
hi, when speaking about Al-Khawarizmi book in page 2
"The Compendious Book on Calculation by Completion and Balancing"
which is in arabic
"Al-Kitab al-mukhtasar fi hisab al-jabr wa-l-muqabala"
"al-mukhtasar" means the compendious
as we can find here : https://search.worldcat.org/fr/title/kitab-al-mukhtasar-fi-hisab-al-jabr-wa-l-muqabala-by-muhammad-ibn-musa-al-khwarizmi-western-translations-and-adaptations-texts-and-studies/oclc/876591333?referer=di&ht=edition
.
but we also have the short title version "Kitab al-Jabr wa-l-Muqabala" without "al" before "Kitab"
.
as we can find here in the summary : https://www.loc.gov/item/2021666184/
.
Thank you !

**Comment by mykelk** [comment]
It appears both ways in various sources, but it appears to be more common with "al-" in front.

**Comment by tZougari** [comment]
we don't say in arabic "Al Kitab al-Jabr wal-Muqabala" .. arabic is my native tongue
Al Kitab = الكتاب
Kitab = كتاب
.
if you have only one arabic version with "Al" i 'll be happy to see it
.
in all the following arabic editions we have "كتاب الجبر و المقابلة" 
<img width="886" alt="khawarizmi" src="https://github.com/algorithmsbooks/optimization/assets/150387897/f71e0c07-d588-44ee-882e-a3f25484584f">
.
excuse me for insisting ! THANKS

**Comment by mykelk** [comment]
Got it. Does that mean that this is wrong?
https://en.wikipedia.org/wiki/Al-Jabr

Is the proposal to simply replace "Al Kitab al-Jabr wal-Muqabala" with "Kitab al-Jabr wal-Muqabala"?

**Comment by tZougari** [comment]
the answer to the second question is yes : )
.
the answer to the first is no. am saying the same thing
see note b :  The Arabic title is sometimes condensed to Hisab al-Jabr wal-Muqabalah or Kitab al-Jabr wal-Muqabalah

**Comment by mykelk** [comment]
And thanks for reporting this!
