### ISSUE TITLE
Page 141-143, $\mu$ of rank-$\mu$ should be $m_{elite}$?

### ISSUE THREAD

**Issue by yeliqseu** [algorithmsbooks/optimization#98]
In Section 8.6 Covariance Matrix Adaptation (CMA), the scalar $\mu$ of the $\text{rank}-\mu$ update is not defined. From the context of the CMA, is this $\mu$ actually $m_{elite}$? In Algorithm 8.9, $m$ is used for the third term of the right-hand side of (8.30).

**Comment by tawheeler** [comment]
Looking at [the CMA paper,](https://arxiv.org/pdf/1604.00772) they define mu as
![image](https://github.com/user-attachments/assets/290f6fb6-cf7b-4f40-a17f-82f8fbffc9cc)

That means that yes, their mu is the number of elite samples.

Good catch on our use of mu in eq 8.30. Will update that to refer to m_elite.

**Comment by tawheeler** [comment]
After the update:

![2024-10-30_21-37](https://github.com/user-attachments/assets/8f2e60a7-2cea-404b-a15a-98a5d4a603ea)
